### ISSUE TITLE
So, this project no longer exists?

### ISSUE THREAD

**Issue by roselmamendes** [NinaDaPraia/Nina#19]
As Will said in email. We can delete this repo.

Why this decision? Thoughts?

@nicolastrres @sephioh @willmendesneto @arthurms

**Comment by RobertBornemann** [comment]
We will have a meeting about this on Friday to discuss the issue with everyone involved and interested. We will proceed from there with a permanent decision based on  this discussion.

**Comment by roselmamendes** [comment]
:+1: @RobertBornemann
