### ISSUE TITLE
SPIKE: Who contract who? 

### ISSUE THREAD

**Issue by RobertBornemann** [NinaDaPraia/Nina#53]

**Comment by nicolastrres** [comment]
@RobertBornemann @sephioh what are expecting on this card?

**Comment by nicolastrres** [comment]
I was talking with @sephioh yesterday, and we think that the client should contract the api.  But I am not sure what should be the output of this. Maybe a json contract created by the client that we can use in our contract tests in the api side?

**Comment by nicolastrres** [comment]
I was talking with @sephioh, we should add to the documentation that we are accepting pull requests with contracts, so if someone start using our API, we create tests using those contracts.
