### ISSUE TITLE
Start to define project's structure of the new client

### ISSUE THREAD

**Issue by roselmamendes** [NinaDaPraia/Nina#64]
This card is aimed to collect ideas for project's structure.
And then start push to repo on Github.

Based on my research about good patterns for project's structure using AngularJS, I found this document: Best Practice Recommendations for Angular App Structure.
I will follow the example for simple projects.

'sampleapp/                 the client app and its unit tests live under this directory
   app.css
   app.js
   app-controller.js
   app-controller_test.js
   components/        module def'n, services, directives, filters, and related
   foo/                files live here. "foo" describes what the module does.
            foo.js     The 'foo' module is defined here.
              foo-directive.js
              foo-directive_test.js
              foo-service.js
              foo-service_test.js
   index.html
e2e-tests/                                e2etests are outside the scope of this
sampleapp-backend/                        proposal, but could be at the same level as
backend/ and sampleapp/... we leave this
up to the developer. '

About the tools to support us in the beginning, I suggest to use: 

Karma (test runner) - karma.conf.js
NodeJS (to run the tasks and install dependencies) - package.json

**Comment by RobertBornemann** [comment]
How can I help providing some support?

**Comment by roselmamendes** [comment]
Pairing w/ me :)

**Comment by RobertBornemann** [comment]
(y)
